# 1. Base image: Python in Linux
FROM python:3.11-slim

# 2. Zet werkdirectory in de container
WORKDIR /app

# 3. Kopieer dependency file
COPY requirements.txt /app/backend/requirements.txt

# 4. Installeer dependencies
RUN pip install --no-cache-dir -r /app/backend/requirements.txt

# 5. Kopieer de rest van de code
COPY . /app/backend

# 6. Expose Streamlit port
EXPOSE 8000

# 7. Start Streamlit
CMD ["uvicorn", "backend.rest_api.app:app", "--host", "0.0.0.0", "--port", "8000"]
