# 1. Base image: Python in Linux
FROM python:3.11-slim

# 2. Zet werkdirectory in de container
WORKDIR /app

# 3. Kopieer dependency file
COPY requirements.txt .

# 4. Installeer dependencies
RUN pip install --no-cache-dir -r requirements.txt

# 5. Kopieer de rest van de code
COPY . .

# 6. Expose Streamlit port
EXPOSE 8501

# 7. Start Streamlit
CMD ["streamlit", "run", "main.py", "--server.port=8501", "--server.address=0.0.0.0", "--server.enableCORS=false", "--server.enableXsrfProtection=false"]
